// Auto-generated by `mcp__supabase__generate_typescript_types` on 2026-05-20.
// To regenerate: run the Supabase MCP tool against project atbkdxmxuqorebrttzma.
// Do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.1"
  }
  public: {
    Tables: {
      _fk_repoint_log_20260518: {
        Row: {
          fk_column: string
          id: string
          new_target: string
          old_target: string
          redirected_at: string
          row_id: string
          table_name: string
        }
        Insert: {
          fk_column: string
          id?: string
          new_target: string
          old_target: string
          redirected_at?: string
          row_id: string
          table_name: string
        }
        Update: {
          fk_column?: string
          id?: string
          new_target?: string
          old_target?: string
          redirected_at?: string
          row_id?: string
          table_name?: string
        }
        Relationships: []
      }
      _vehicles_new_archive_20260518: {
        Row: {
          acceleration: number | null
          brand_id: string
          cargo_capacity: number | null
          co2_emissions: number | null
          coup_de_coeur_category: string | null
          coup_de_coeur_reason: string | null
          created_at: string | null
          cylinders: number | null
          dimensions: Json | null
          doors: number | null
          engine_size: number | null
          euro_norm: string | null
          exterior_color: string | null
          features: Json | null
          fuel_consumption_city: number | null
          fuel_consumption_combined: number | null
          fuel_consumption_highway: number | null
          fuel_type: string | null
          horsepower: number | null
          id: string
          images: Json | null
          interior_color: string | null
          is_available: boolean | null
          is_coming_soon: boolean | null
          is_coup_de_coeur: boolean
          is_featured_offer: boolean
          is_new_release: boolean | null
          is_popular: boolean | null
          launch_date: string | null
          mileage: number | null
          model_id: string
          power_kw: number | null
          price_max: number | null
          price_min: number | null
          safety_features: Json | null
          seating_capacity: number | null
          source_url: string | null
          top_speed: number | null
          torque: number | null
          transmission: string | null
          updated_at: string | null
          variant_list: Json | null
          vat_deductible: boolean | null
          version: string | null
          views: number | null
          warranty_months: number | null
          year: number
        }
        Insert: {
          acceleration?: number | null
          brand_id: string
          cargo_capacity?: number | null
          co2_emissions?: number | null
          coup_de_coeur_category?: string | null
          coup_de_coeur_reason?: string | null
          created_at?: string | null
          cylinders?: number | null
          dimensions?: Json | null
          doors?: number | null
          engine_size?: number | null
          euro_norm?: string | null
          exterior_color?: string | null
          features?: Json | null
          fuel_consumption_city?: number | null
          fuel_consumption_combined?: number | null
          fuel_consumption_highway?: number | null
          fuel_type?: string | null
          horsepower?: number | null
          id?: string
          images?: Json | null
          interior_color?: string | null
          is_available?: boolean | null
          is_coming_soon?: boolean | null
          is_coup_de_coeur?: boolean
          is_featured_offer?: boolean
          is_new_release?: boolean | null
          is_popular?: boolean | null
          launch_date?: string | null
          mileage?: number | null
          model_id: string
          power_kw?: number | null
          price_max?: number | null
          price_min?: number | null
          safety_features?: Json | null
          seating_capacity?: number | null
          source_url?: string | null
          top_speed?: number | null
          torque?: number | null
          transmission?: string | null
          updated_at?: string | null
          variant_list?: Json | null
          vat_deductible?: boolean | null
          version?: string | null
          views?: number | null
          warranty_months?: number | null
          year: number
        }
        Update: {
          acceleration?: number | null
          brand_id?: string
          cargo_capacity?: number | null
          co2_emissions?: number | null
          coup_de_coeur_category?: string | null
          coup_de_coeur_reason?: string | null
          created_at?: string | null
          cylinders?: number | null
          dimensions?: Json | null
          doors?: number | null
          engine_size?: number | null
          euro_norm?: string | null
          exterior_color?: string | null
          features?: Json | null
          fuel_consumption_city?: number | null
          fuel_consumption_combined?: number | null
          fuel_consumption_highway?: number | null
          fuel_type?: string | null
          horsepower?: number | null
          id?: string
          images?: Json | null
          interior_color?: string | null
          is_available?: boolean | null
          is_coming_soon?: boolean | null
          is_coup_de_coeur?: boolean
          is_featured_offer?: boolean
          is_new_release?: boolean | null
          is_popular?: boolean | null
          launch_date?: string | null
          mileage?: number | null
          model_id?: string
          power_kw?: number | null
          price_max?: number | null
          price_min?: number | null
          safety_features?: Json | null
          seating_capacity?: number | null
          source_url?: string | null
          top_speed?: number | null
          torque?: number | null
          transmission?: string | null
          updated_at?: string | null
          variant_list?: Json | null
          vat_deductible?: boolean | null
          version?: string | null
          views?: number | null
          warranty_months?: number | null
          year?: number
        }
        Relationships: []
      }
      articles: {
        Row: {
          author_id: string | null
          category: string | null
          content: string
          created_at: string | null
          excerpt: string | null
          featured_image: string | null
          id: string
          is_published: boolean | null
          published_at: string | null
          slug: string
          tags: Json | null
          title: string
          updated_at: string | null
          views: number | null
        }
        Insert: {
          author_id?: string | null
          category?: string | null
          content: string
          created_at?: string | null
          excerpt?: string | null
          featured_image?: string | null
          id?: string
          is_published?: boolean | null
          published_at?: string | null
          slug: string
          tags?: Json | null
          title: string
          updated_at?: string | null
          views?: number | null
        }
        Update: {
          author_id?: string | null
          category?: string | null
          content?: string
          created_at?: string | null
          excerpt?: string | null
          featured_image?: string | null
          id?: string
          is_published?: boolean | null
          published_at?: string | null
          slug?: string
          tags?: Json | null
          title?: string
          updated_at?: string | null
          views?: number | null
        }
        Relationships: []
      }
      blog_images: {
        Row: {
          alt_text: string | null
          blog_post_id: string
          caption: string | null
          created_at: string | null
          display_order: number | null
          float_position: string | null
          id: string
          image_url: string
          size: string | null
        }
        Insert: {
          alt_text?: string | null
          blog_post_id: string
          caption?: string | null
          created_at?: string | null
          display_order?: number | null
          float_position?: string | null
          id?: string
          image_url: string
          size?: string | null
        }
        Update: {
          alt_text?: string | null
          blog_post_id?: string
          caption?: string | null
          created_at?: string | null
          display_order?: number | null
          float_position?: string | null
          id?: string
          image_url?: string
          size?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "blog_images_blog_post_id_fkey"
            columns: ["blog_post_id"]
            isOneToOne: false
            referencedRelation: "blog_posts"
            referencedColumns: ["id"]
          },
        ]
      }
      blog_posts: {
        Row: {
          author: string | null
          category: string
          content: string
          created_at: string | null
          featured: boolean | null
          hero_image_caption: string | null
          hero_image_url: string | null
          id: string
          meta_description: string | null
          published_at: string | null
          slug: string
          status: string
          subtitle: string | null
          tags: string[] | null
          title: string
          updated_at: string | null
          views: number | null
        }
        Insert: {
          author?: string | null
          category: string
          content: string
          created_at?: string | null
          featured?: boolean | null
          hero_image_caption?: string | null
          hero_image_url?: string | null
          id?: string
          meta_description?: string | null
          published_at?: string | null
          slug: string
          status?: string
          subtitle?: string | null
          tags?: string[] | null
          title: string
          updated_at?: string | null
          views?: number | null
        }
        Update: {
          author?: string | null
          category?: string
          content?: string
          created_at?: string | null
          featured?: boolean | null
          hero_image_caption?: string | null
          hero_image_url?: string | null
          id?: string
          meta_description?: string | null
          published_at?: string | null
          slug?: string
          status?: string
          subtitle?: string | null
          tags?: string[] | null
          title?: string
          updated_at?: string | null
          views?: number | null
        }
        Relationships: []
      }
      brands: {
        Row: {
          created_at: string | null
          description: string | null
          id: string
          logo_url: string | null
          name: string
          origin: string | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          id?: string
          logo_url?: string | null
          name: string
          origin?: string | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          id?: string
          logo_url?: string | null
          name?: string
          origin?: string | null
        }
        Relationships: []
      }
      comparisons: {
        Row: {
          created_at: string | null
          id: string
          is_public: boolean | null
          name: string
          user_id: string
          vehicle_ids: Json
        }
        Insert: {
          created_at?: string | null
          id?: string
          is_public?: boolean | null
          name: string
          user_id: string
          vehicle_ids: Json
        }
        Update: {
          created_at?: string | null
          id?: string
          is_public?: boolean | null
          name?: string
          user_id?: string
          vehicle_ids?: Json
        }
        Relationships: []
      }
      contact_messages: {
        Row: {
          created_at: string
          email: string
          id: string
          ip_address: unknown
          is_read: boolean
          message: string
          name: string
          phone: string | null
          subject: string
          user_agent: string | null
        }
        Insert: {
          created_at?: string
          email: string
          id?: string
          ip_address?: unknown
          is_read?: boolean
          message: string
          name: string
          phone?: string | null
          subject: string
          user_agent?: string | null
        }
        Update: {
          created_at?: string
          email?: string
          id?: string
          ip_address?: unknown
          is_read?: boolean
          message?: string
          name?: string
          phone?: string | null
          subject?: string
          user_agent?: string | null
        }
        Relationships: []
      }
      dealerships: {
        Row: {
          address: string | null
          brand_id: string | null
          city: string | null
          created_at: string | null
          email: string | null
          id: string
          latitude: number | null
          longitude: number | null
          name: string
          phone: string | null
          website: string | null
        }
        Insert: {
          address?: string | null
          brand_id?: string | null
          city?: string | null
          created_at?: string | null
          email?: string | null
          id?: string
          latitude?: number | null
          longitude?: number | null
          name: string
          phone?: string | null
          website?: string | null
        }
        Update: {
          address?: string | null
          brand_id?: string | null
          city?: string | null
          created_at?: string | null
          email?: string | null
          id?: string
          latitude?: number | null
          longitude?: number | null
          name?: string
          phone?: string | null
          website?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "dealerships_brand_id_fkey"
            columns: ["brand_id"]
            isOneToOne: false
            referencedRelation: "brands"
            referencedColumns: ["id"]
          },
        ]
      }
      energy_rates: {
        Row: {
          created_at: string
          effective_date: string
          id: string
          is_active: boolean
          rate_type: string
          source: string | null
          unit: string
          updated_at: string
          value_dh: number
        }
        Insert: {
          created_at?: string
          effective_date: string
          id?: string
          is_active?: boolean
          rate_type: string
          source?: string | null
          unit: string
          updated_at?: string
          value_dh: number
        }
        Update: {
          created_at?: string
          effective_date?: string
          id?: string
          is_active?: boolean
          rate_type?: string
          source?: string | null
          unit?: string
          updated_at?: string
          value_dh?: number
        }
        Relationships: []
      }
      favorites: {
        Row: {
          created_at: string | null
          id: string
          user_id: string
          vehicle_new_id: string | null
          vehicle_type: string
          vehicle_used_id: string | null
        }
        Insert: {
          created_at?: string | null
          id?: string
          user_id: string
          vehicle_new_id?: string | null
          vehicle_type: string
          vehicle_used_id?: string | null
        }
        Update: {
          created_at?: string | null
          id?: string
          user_id?: string
          vehicle_new_id?: string | null
          vehicle_type?: string
          vehicle_used_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "favorites_vehicle_new_id_fkey"
            columns: ["vehicle_new_id"]
            isOneToOne: false
            referencedRelation: "vehicles_new"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "favorites_vehicle_used_id_fkey"
            columns: ["vehicle_used_id"]
            isOneToOne: false
            referencedRelation: "vehicles_used"
            referencedColumns: ["id"]
          },
        ]
      }
      fiches_techniques: {
        Row: {
          created_at: string
          en_detail: Json
          id: string
          model_id: string
          source_url: string | null
          specs: Json
          updated_at: string
        }
        Insert: {
          created_at?: string
          en_detail?: Json
          id?: string
          model_id: string
          source_url?: string | null
          specs?: Json
          updated_at?: string
        }
        Update: {
          created_at?: string
          en_detail?: Json
          id?: string
          model_id?: string
          source_url?: string | null
          specs?: Json
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "fiches_techniques_model_id_fkey"
            columns: ["model_id"]
            isOneToOne: true
            referencedRelation: "models"
            referencedColumns: ["id"]
          },
        ]
      }
      forum_categories: {
        Row: {
          created_at: string | null
          description: string | null
          icon: string | null
          id: string
          name: string
          order_position: number | null
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          icon?: string | null
          id?: string
          name: string
          order_position?: number | null
        }
        Update: {
          created_at?: string | null
          description?: string | null
          icon?: string | null
          id?: string
          name?: string
          order_position?: number | null
        }
        Relationships: []
      }
      forum_posts: {
        Row: {
          content: string
          created_at: string | null
          id: string
          parent_id: string | null
          topic_id: string
          updated_at: string | null
          user_id: string
        }
        Insert: {
          content: string
          created_at?: string | null
          id?: string
          parent_id?: string | null
          topic_id: string
          updated_at?: string | null
          user_id: string
        }
        Update: {
          content?: string
          created_at?: string | null
          id?: string
          parent_id?: string | null
          topic_id?: string
          updated_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "forum_posts_parent_id_fkey"
            columns: ["parent_id"]
            isOneToOne: false
            referencedRelation: "forum_posts"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "forum_posts_topic_id_fkey"
            columns: ["topic_id"]
            isOneToOne: false
            referencedRelation: "forum_topics"
            referencedColumns: ["id"]
          },
        ]
      }
      forum_topics: {
        Row: {
          category_id: string
          content: string
          created_at: string | null
          id: string
          is_locked: boolean | null
          is_pinned: boolean | null
          title: string
          updated_at: string | null
          user_id: string
          views: number | null
        }
        Insert: {
          category_id: string
          content: string
          created_at?: string | null
          id?: string
          is_locked?: boolean | null
          is_pinned?: boolean | null
          title: string
          updated_at?: string | null
          user_id: string
          views?: number | null
        }
        Update: {
          category_id?: string
          content?: string
          created_at?: string | null
          id?: string
          is_locked?: boolean | null
          is_pinned?: boolean | null
          title?: string
          updated_at?: string | null
          user_id?: string
          views?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "forum_topics_category_id_fkey"
            columns: ["category_id"]
            isOneToOne: false
            referencedRelation: "forum_categories"
            referencedColumns: ["id"]
          },
        ]
      }
      magazines: {
        Row: {
          cover_url: string
          created_at: string
          dossier_subtitle: string | null
          dossier_title: string
          id: string
          is_published: boolean
          issue_date: string | null
          issue_number: number
          order_position: number
          pdf_url: string
          publication: string
          tags: Json
          updated_at: string
        }
        Insert: {
          cover_url: string
          created_at?: string
          dossier_subtitle?: string | null
          dossier_title: string
          id?: string
          is_published?: boolean
          issue_date?: string | null
          issue_number: number
          order_position: number
          pdf_url: string
          publication: string
          tags?: Json
          updated_at?: string
        }
        Update: {
          cover_url?: string
          created_at?: string
          dossier_subtitle?: string | null
          dossier_title?: string
          id?: string
          is_published?: boolean
          issue_date?: string | null
          issue_number?: number
          order_position?: number
          pdf_url?: string
          publication?: string
          tags?: Json
          updated_at?: string
        }
        Relationships: []
      }
      models: {
        Row: {
          brand_id: string | null
          category: string | null
          created_at: string | null
          id: string
          name: string
        }
        Insert: {
          brand_id?: string | null
          category?: string | null
          created_at?: string | null
          id?: string
          name: string
        }
        Update: {
          brand_id?: string | null
          category?: string | null
          created_at?: string | null
          id?: string
          name?: string
        }
        Relationships: [
          {
            foreignKeyName: "models_brand_id_fkey"
            columns: ["brand_id"]
            isOneToOne: false
            referencedRelation: "brands"
            referencedColumns: ["id"]
          },
        ]
      }
      narsa_videos: {
        Row: {
          created_at: string | null
          description: string | null
          duration: string | null
          id: string
          is_published: boolean | null
          order_position: number | null
          thumbnail_url: string | null
          title: string
          updated_at: string | null
          video_url: string
        }
        Insert: {
          created_at?: string | null
          description?: string | null
          duration?: string | null
          id?: string
          is_published?: boolean | null
          order_position?: number | null
          thumbnail_url?: string | null
          title: string
          updated_at?: string | null
          video_url: string
        }
        Update: {
          created_at?: string | null
          description?: string | null
          duration?: string | null
          id?: string
          is_published?: boolean | null
          order_position?: number | null
          thumbnail_url?: string | null
          title?: string
          updated_at?: string | null
          video_url?: string
        }
        Relationships: []
      }
      newsletter_subscribers: {
        Row: {
          email: string
          id: string
          is_active: boolean | null
          subscribed_at: string | null
        }
        Insert: {
          email: string
          id?: string
          is_active?: boolean | null
          subscribed_at?: string | null
        }
        Update: {
          email?: string
          id?: string
          is_active?: boolean | null
          subscribed_at?: string | null
        }
        Relationships: []
      }
      profiles: {
        Row: {
          avatar_url: string | null
          bio: string | null
          city: string | null
          created_at: string | null
          full_name: string | null
          id: string
          is_admin: boolean | null
          is_dealer: boolean | null
          phone: string | null
          updated_at: string | null
        }
        Insert: {
          avatar_url?: string | null
          bio?: string | null
          city?: string | null
          created_at?: string | null
          full_name?: string | null
          id: string
          is_admin?: boolean | null
          is_dealer?: boolean | null
          phone?: string | null
          updated_at?: string | null
        }
        Update: {
          avatar_url?: string | null
          bio?: string | null
          city?: string | null
          created_at?: string | null
          full_name?: string | null
          id?: string
          is_admin?: boolean | null
          is_dealer?: boolean | null
          phone?: string | null
          updated_at?: string | null
        }
        Relationships: []
      }
      promotions: {
        Row: {
          created_at: string | null
          dealership_id: string | null
          description: string | null
          discount_amount: number | null
          discount_percentage: number | null
          id: string
          image_url: string | null
          is_active: boolean | null
          terms: string | null
          title: string
          valid_from: string
          valid_until: string
          vehicle_id: string
        }
        Insert: {
          created_at?: string | null
          dealership_id?: string | null
          description?: string | null
          discount_amount?: number | null
          discount_percentage?: number | null
          id?: string
          image_url?: string | null
          is_active?: boolean | null
          terms?: string | null
          title: string
          valid_from: string
          valid_until: string
          vehicle_id: string
        }
        Update: {
          created_at?: string | null
          dealership_id?: string | null
          description?: string | null
          discount_amount?: number | null
          discount_percentage?: number | null
          id?: string
          image_url?: string | null
          is_active?: boolean | null
          terms?: string | null
          title?: string
          valid_from?: string
          valid_until?: string
          vehicle_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "promotions_dealership_id_fkey"
            columns: ["dealership_id"]
            isOneToOne: false
            referencedRelation: "dealerships"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "promotions_vehicle_id_fkey"
            columns: ["vehicle_id"]
            isOneToOne: false
            referencedRelation: "vehicles_new"
            referencedColumns: ["id"]
          },
        ]
      }
      service_bookings: {
        Row: {
          city: string
          created_at: string
          id: string
          notes: string | null
          phone: string
          plate_number: string
          preferred_date: string
          service_type: string
          status: string
        }
        Insert: {
          city: string
          created_at?: string
          id?: string
          notes?: string | null
          phone: string
          plate_number: string
          preferred_date: string
          service_type: string
          status?: string
        }
        Update: {
          city?: string
          created_at?: string
          id?: string
          notes?: string | null
          phone?: string
          plate_number?: string
          preferred_date?: string
          service_type?: string
          status?: string
        }
        Relationships: []
      }
      vehicles_new: {
        Row: {
          acceleration: number | null
          brand_id: string
          cargo_capacity: number | null
          co2_emissions: number | null
          coup_de_coeur_category: string | null
          coup_de_coeur_reason: string | null
          created_at: string | null
          cylinders: number | null
          dimensions: Json | null
          doors: number | null
          engine_size: number | null
          euro_norm: string | null
          exterior_color: string | null
          features: Json | null
          fuel_consumption_city: number | null
          fuel_consumption_combined: number | null
          fuel_consumption_highway: number | null
          fuel_type: string | null
          horsepower: number | null
          id: string
          images: Json | null
          interior_color: string | null
          is_available: boolean | null
          is_coming_soon: boolean | null
          is_coup_de_coeur: boolean
          is_featured_offer: boolean
          is_new_release: boolean | null
          is_popular: boolean | null
          launch_date: string | null
          mileage: number | null
          model_id: string
          power_kw: number | null
          price_max: number | null
          price_min: number | null
          safety_features: Json | null
          seating_capacity: number | null
          source_url: string | null
          top_speed: number | null
          torque: number | null
          transmission: string | null
          updated_at: string | null
          variant_list: Json | null
          vat_deductible: boolean | null
          version: string | null
          views: number | null
          warranty_months: number | null
          year: number
        }
        Insert: {
          acceleration?: number | null
          brand_id: string
          cargo_capacity?: number | null
          co2_emissions?: number | null
          coup_de_coeur_category?: string | null
          coup_de_coeur_reason?: string | null
          created_at?: string | null
          cylinders?: number | null
          dimensions?: Json | null
          doors?: number | null
          engine_size?: number | null
          euro_norm?: string | null
          exterior_color?: string | null
          features?: Json | null
          fuel_consumption_city?: number | null
          fuel_consumption_combined?: number | null
          fuel_consumption_highway?: number | null
          fuel_type?: string | null
          horsepower?: number | null
          id?: string
          images?: Json | null
          interior_color?: string | null
          is_available?: boolean | null
          is_coming_soon?: boolean | null
          is_coup_de_coeur?: boolean
          is_featured_offer?: boolean
          is_new_release?: boolean | null
          is_popular?: boolean | null
          launch_date?: string | null
          mileage?: number | null
          model_id: string
          power_kw?: number | null
          price_max?: number | null
          price_min?: number | null
          safety_features?: Json | null
          seating_capacity?: number | null
          source_url?: string | null
          top_speed?: number | null
          torque?: number | null
          transmission?: string | null
          updated_at?: string | null
          variant_list?: Json | null
          vat_deductible?: boolean | null
          version?: string | null
          views?: number | null
          warranty_months?: number | null
          year: number
        }
        Update: {
          acceleration?: number | null
          brand_id?: string
          cargo_capacity?: number | null
          co2_emissions?: number | null
          coup_de_coeur_category?: string | null
          coup_de_coeur_reason?: string | null
          created_at?: string | null
          cylinders?: number | null
          dimensions?: Json | null
          doors?: number | null
          engine_size?: number | null
          euro_norm?: string | null
          exterior_color?: string | null
          features?: Json | null
          fuel_consumption_city?: number | null
          fuel_consumption_combined?: number | null
          fuel_consumption_highway?: number | null
          fuel_type?: string | null
          horsepower?: number | null
          id?: string
          images?: Json | null
          interior_color?: string | null
          is_available?: boolean | null
          is_coming_soon?: boolean | null
          is_coup_de_coeur?: boolean
          is_featured_offer?: boolean
          is_new_release?: boolean | null
          is_popular?: boolean | null
          launch_date?: string | null
          mileage?: number | null
          model_id?: string
          power_kw?: number | null
          price_max?: number | null
          price_min?: number | null
          safety_features?: Json | null
          seating_capacity?: number | null
          source_url?: string | null
          top_speed?: number | null
          torque?: number | null
          transmission?: string | null
          updated_at?: string | null
          variant_list?: Json | null
          vat_deductible?: boolean | null
          version?: string | null
          views?: number | null
          warranty_months?: number | null
          year?: number
        }
        Relationships: [
          {
            foreignKeyName: "vehicles_new_brand_id_fkey"
            columns: ["brand_id"]
            isOneToOne: false
            referencedRelation: "brands"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vehicles_new_model_id_fkey"
            columns: ["model_id"]
            isOneToOne: false
            referencedRelation: "models"
            referencedColumns: ["id"]
          },
        ]
      }
      vehicles_used: {
        Row: {
          brand_id: string
          city: string
          color: string | null
          condition: string | null
          contact_email: string
          contact_phone: string
          created_at: string | null
          description: string
          fuel_type: string | null
          id: string
          images: Json | null
          is_active: boolean | null
          is_featured: boolean | null
          is_sold: boolean | null
          mileage: number
          model_id: string
          price: number
          seller_type: string | null
          transmission: string | null
          updated_at: string | null
          user_id: string
          views: number | null
          year: number
        }
        Insert: {
          brand_id: string
          city: string
          color?: string | null
          condition?: string | null
          contact_email: string
          contact_phone: string
          created_at?: string | null
          description: string
          fuel_type?: string | null
          id?: string
          images?: Json | null
          is_active?: boolean | null
          is_featured?: boolean | null
          is_sold?: boolean | null
          mileage: number
          model_id: string
          price: number
          seller_type?: string | null
          transmission?: string | null
          updated_at?: string | null
          user_id: string
          views?: number | null
          year: number
        }
        Update: {
          brand_id?: string
          city?: string
          color?: string | null
          condition?: string | null
          contact_email?: string
          contact_phone?: string
          created_at?: string | null
          description?: string
          fuel_type?: string | null
          id?: string
          images?: Json | null
          is_active?: boolean | null
          is_featured?: boolean | null
          is_sold?: boolean | null
          mileage?: number
          model_id?: string
          price?: number
          seller_type?: string | null
          transmission?: string | null
          updated_at?: string | null
          user_id?: string
          views?: number | null
          year?: number
        }
        Relationships: [
          {
            foreignKeyName: "vehicles_used_brand_id_fkey"
            columns: ["brand_id"]
            isOneToOne: false
            referencedRelation: "brands"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "vehicles_used_model_id_fkey"
            columns: ["model_id"]
            isOneToOne: false
            referencedRelation: "models"
            referencedColumns: ["id"]
          },
        ]
      }
      videos: {
        Row: {
          category: string | null
          created_at: string | null
          description: string | null
          duration: string | null
          id: string
          is_published: boolean | null
          thumbnail_url: string | null
          title: string
          vehicle_id: string | null
          video_url: string
          views: number | null
        }
        Insert: {
          category?: string | null
          created_at?: string | null
          description?: string | null
          duration?: string | null
          id?: string
          is_published?: boolean | null
          thumbnail_url?: string | null
          title: string
          vehicle_id?: string | null
          video_url: string
          views?: number | null
        }
        Update: {
          category?: string | null
          created_at?: string | null
          description?: string | null
          duration?: string | null
          id?: string
          is_published?: boolean | null
          thumbnail_url?: string | null
          title?: string
          vehicle_id?: string | null
          video_url?: string
          views?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "videos_vehicle_id_fkey"
            columns: ["vehicle_id"]
            isOneToOne: false
            referencedRelation: "vehicles_new"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      collapse_vehicles_to_one_per_model: {
        Args: { plan: Json }
        Returns: Json
      }
      increment_article_views: {
        Args: { article_id: string }
        Returns: undefined
      }
      increment_blog_post_views: {
        Args: { post_id: string }
        Returns: undefined
      }
      increment_forum_topic_views: {
        Args: { topic_id: string }
        Returns: undefined
      }
      increment_used_vehicle_views: {
        Args: { vehicle_id: string }
        Returns: undefined
      }
      increment_vehicle_views: {
        Args: { vehicle_id: string }
        Returns: undefined
      }
      increment_video_views: { Args: { video_id: string }; Returns: undefined }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
